#All the configurations are added in department-service.yaml(name that we specify below should match) file of config-server repository
spring:
  application:
    name: department-service
  config:
    import: "optional:configserver:http://localhost:8088"
