server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://localhost:8761/eureka/ , http://localhost:8762/eureka/
#We can define 2 eureka servers and run two service registry eureka servers. For more details refer readme.md

#For ZipKin
management:
  tracing:
    sampling:
      probability: 1.0