server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ , http://localhost:8762/eureka/

#For ZipKin
management:
  tracing:
    sampling:
      probability: 1.0