server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#For ZipKin
spring:
  zipkin:
    base-url: http://localhost:9411/

#100% of the requests will be traced.
#management:
#  tracing:
#  sampling:
#    probability: 1.0

#Dependencies for Circuit breaker starts
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      employeeFindById:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
#Dependencies for Circuit breaker ends

logging:
  file: C:/Users/rajvi/Desktop/logging.log